# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 628c28b13c59a8126b5b4bbc7432b99dea07878c7b348cf09ac8de332b6cbf01ec99710a91539bdaf4dc916c02d4b1aeadfb29cb915c024f00ade6463b012585

test:
  secret_key_base: b31927d4d28249a6443e318ed99bf9069b9b067862d252f3cd13687aa997b5c36514590639bb6fa52284a05ed08975a7824d32ed9328479fad63a222c27e47f2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
